name: DesignCode

on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
  workflow_dispatch:
jobs:
  
  sync_data:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subekti404dev/github-action-vault-secret@v1
        id: vault
        with:
          base-url: "${{ secrets.VAULT_BASE_URL }}"
          path: "${{ secrets.VAULT_PATH }}"
          token: "${{ secrets.VAULT_TOKEN }}"
          key: "DOTENV"
          to-file: ".env"
        
      - name: Create Temporary Directory
        run: mkdir videos
        
      - name: Install Dependencies
        run: npm install
        
      - name: Doing Magic Here...
        run: node scripts/design-code.js
  
      - name: LS
        run: ls -la videos/

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: ${{ github.event.inputs.name }}
      #     path: videos/
