name: Docker Torrent Download
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Torrent file URL'
        required: true
jobs:
  download:
    runs-on: ubuntu-latest
    container: subekti13/torrent-downloader:latest
    steps:
    
        - uses: subekti404dev/github-action-vault-secret@v1
          id: vault
          with:
            base-url: "${{ secrets.VAULT_BASE_URL }}"
            path: "${{ secrets.VAULT_PATH }}"
            token: "${{ secrets.VAULT_TOKEN }}"
            key: "DOTENV"
       
        - name: Write .env File
          run: |
              echo '${{ steps.vault.outputs.data }}' >> .env
        
          
        - name: Dowload File
          run: node /app/download.js ${{ github.event.inputs.url }}
      
        - name: LS
          run: cd /data && ls -la
          
        - name: Upload to Drive
          run: node /app/upload.js

