name: Download to drive
on:
  # repository_dispatch:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL file'
        required: true
      filename:
        description: 'Filename'
        required: false
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: subekti404dev/github-action-vault-secret@v1
        id: vault
        with:
            base-url: "${{ secrets.VAULT_BASE_URL }}"
            path: "${{ secrets.VAULT_PATH }}"
            token: "${{ secrets.VAULT_TOKEN }}"
            key: "DOTENV"
            to-file: ".env"
      
      - name: Install Dependencies
        run: npm install
        
      - name: Dowload File
        run: node scripts/download-to-drive.js ${{ github.event.inputs.url }} ${{ github.event.inputs.filename }}
