name: Send Back The Env
on:
  repository_dispatch:
  workflow_dispatch:
jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Write .env File
        run: |
            echo '${{ secrets.DOTENV }}' >> .env
      
      - name: Install Dependencies
        run: npm install
        
      - name: Send The Env
        run: node scripts/send-me-back-env.js
